name: 'Setup Humanitec CLI'
description: 'GitHub Action to set up the Humanitec CLI'
author: 'humanitec'

branding:
  icon: 'check-square'
  color: 'blue'

inputs:
  version:
    description: 'CLI version to install'
    required: true

outputs: {}

runs:
  using: node20
  main: dist/index.js
